import { createSlice } from '@reduxjs/toolkit';

const createMasterProductSlice = createSlice({
  name: 'masterProduct',
  initialState: {
    list: [
      {
        id: '1',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '2',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '3',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '4',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '5',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '6',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '7',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '8',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '9',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '10',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F1',
        currency: 'Rupiah',
        productDescription: 'Asia 50 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '11',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 100 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '12',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '13',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '14',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '15',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 510 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '16',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: ' Single',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '17',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '18',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Group',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '19',
        productId: '13562452',
        productCode: 'OTR',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family 100 test',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '20',
        productId: '13562452',
        productCode: 'OT',
        productDetailCode: 'A1F122',
        currency: 'Rupiah',
        productDescription: 'Asia 150 Family test	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Family',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
      {
        id: '21',
        productId: '1114566',
        productCode: 'OTS',
        productDetailCode: 'A1F123',
        currency: 'Rupiah',
        productDescription: 'Asia 250 Family	',
        personalAccidentCover: 'Coverage up to Rp. 50.000.000,-',
        medicalCover: 'Coverage up to Rp. 50.000.000,',
        travelCover: 'Coverage up to Rp. 50.000.000,-',
        productType: 'Single',
        travelDuration: '1 - 5 days',
        additionalWeek: '-',
        updatedData: '27/10/20, at 13:54 PM',
      },
    ],
    formProduct: {
      productCode: '',
      productName: '',
      productType: '',
      currId: '',
      productDetailCode: '',
      productDescription: '',
      personalAccidentCover: '',
      productMedicalCover: '',
      productTravelCover: '',
      additionalWeek: '',
      planType: '',
      groupArea: '',
      travelDuration: '',
    },
    selection: [],
    planType: [
      {
        id: 1,
        label: '50',
        value: '50',
      },
      {
        id: 2,
        label: '100',
        value: '100',
      },
      {
        id: 3,
        label: '150',
        value: '150',
      },
    ],
    productTypes: [
      {
        id: 1,
        label: 'Family',
        value: 'Family',
      },
      {
        id: 2,
        label: 'Individual',
        value: 'Individual',
      },
      {
        id: 3,
        label: 'Group',
        value: 'Group',
      },
    ],
    travelDurations: [
      {
        id: 1,
        label: '1-5 days',
        value: '1-5 days',
      },
      {
        id: 2,
        label: '6-8 days',
        value: '6-8 days',
      },
      {
        id: 3,
        label: '9-11 days',
        value: '9-11 days',
      },
    ],
    additonalList: [
      {
        id: 1,
        label: 'Asia 50 Family ',
        value: 'Asia 50 Family ',
      },
      {
        id: 2,
        label: 'Asia 50 Individual ',
        value: 'Asia 50 Individual ',
      },
      {
        id: 3,
        label: 'Worldwide 50 Family ',
        value: 'Worldwide 50 Family ',
      },
      {
        id: 4,
        label: 'Worldwide 50 Individual ',
        value: 'Worldwide 50 Individual ',
      },
      {
        id: 5,
        label: 'Worldwide 100 Family ',
        value: 'Worldwide 100 Family ',
      },
      {
        id: 6,
        label: 'Worldwide 100 Individual ',
        value: 'Worldwide 100 Individual ',
      },
    ],
    groupAreaList: [
      {
        id: 1,
        label: 'Area 1',
        value: 'Area 1 ',
      },
      {
        id: 2,
        label: 'Area 2',
        value: 'Area 2 ',
      },
      {
        id: 3,
        label: 'Area 3',
        value: 'Area 3 ',
      },
    ],
  },
  reducers: {
    setMasterProduct: (state, action) => {
      state.list = action.payload;
    },
    setListSelectProduct: (state, action) => {
      state.selection = action.payload;
    },
    setProductForm: (state, action) => {
      state.formProduct = action.payload;
    },
  },
});

export const { setProductForm, setMasterProduct, setListSelectProduct } =
  createMasterProductSlice.actions;

export default createMasterProductSlice.reducer;
export const listProduct = (state) => state.masterProduct.list;
export const listProductSelection = (state) => state.masterProduct.selection;
export const formProduct = (state) => state.masterProduct.formProduct;
export const listAdditonal = (state) => state.masterProduct.additonalList;
export const typeProd = (state) => state.masterProduct.productTypes;
export const planTypes = (state) => state.masterProduct.planType;
export const travelDurations = (state) => state.masterProduct.travelDurations;
export const areaList = (state) => state.masterProduct.groupAreaList;
