import { createSlice } from "@reduxjs/toolkit"

const createMasterProductSlice = createSlice({
    name: 'masterProduct',
    initialState: {
        list: [
            {
                id: "1",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "2",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "3",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "4",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "5",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "6",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "7",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "8",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "9",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "10",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F1",
                currency: "Rupiah",
                productDescription: "Asia 50 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "11",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 100 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "12",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "13",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "14",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "15",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 510 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "16",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: " Single",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "17",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "18",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Group",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "19",
                productId: "13562452",
                productCode: "OTR",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family 100 test",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "20",
                productId: "13562452",
                productCode: "OT",
                productDetailCode: "A1F122",
                currency: "Rupiah",
                productDescription: "Asia 150 Family test	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Family",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            },
            {
                id: "21",
                productId: "1114566",
                productCode: "OTS",
                productDetailCode: "A1F123",
                currency: "Rupiah",
                productDescription: "Asia 250 Family	",
                personalAccidentCover: "Coverage up to Rp. 50.000.000,-",
                medicalCover: "Coverage up to Rp. 50.000.000,",
                travelCover: "Coverage up to Rp. 50.000.000,-",
                productType: "Single",
                travelDuration: "1 - 5 days",
                additionalWeek: "-",
                updatedData: "27/10/20, at 13:54 PM"
            }
        ],
        selection: [],
        
    },
    reducers: {
        setMasterProduct: (state, action) => {
            state.list = action.payload
        },
        setListSelectProduct: (state, action) => {
            state.selection = action.payload
        },
        
    },
})

export const {setMasterProduct,setListSelectProduct} = createMasterProductSlice.actions

export default createMasterProductSlice.reducer
export const listProduct = (state) => state.masterProduct.list
export const listProductSelection = (state) => state.masterProduct.selection